name: clip_concat_model_full_data_2_classes

train_data: C:\Users\Claire\Documents\UdeM\IFT6759\IFT6759-Fake-news-detection\data\raw\multimodal_only_samples\multimodal_train.tsv
val_data: C:\Users\Claire\Documents\UdeM\IFT6759\IFT6759-Fake-news-detection\data\raw\multimodal_only_samples\multimodal_validate.tsv
image_folder: C:\Users\Claire\Documents\UdeM\IFT6759\IFT6759-Fake-news-detection\data\raw\public_image_set

num_classes: 2

vit_model_name: openai/clip-vit-base-patch32
text_model_name: openai/clip-vit-base-patch32
fusion_method: concat

batch_size: 64
num_epochs: 25
learning_rate: 0.0001
patience: 3  # Early stopping patience

save_dir: C:\Users\Claire\Documents\UdeM\IFT6759\IFT6759-Fake-news-detection_v2\fake_news_detection\logs\clip_concat_model_full_data_2_classes