name: concat_model_test_10k

train_data: C:\Users\Claire\Documents\UdeM\IFT6759\IFT6759-Fake-news-detection\data\raw\multimodal_only_samples\multimodal_train.tsv
val_data: C:\Users\Claire\Documents\UdeM\IFT6759\IFT6759-Fake-news-detection\data\raw\multimodal_only_samples\multimodal_validate.tsv
image_folder: C:\Users\Claire\Documents\UdeM\IFT6759\IFT6759-Fake-news-detection\data\raw\public_image_set

num_classes: 2

batch_size: 16
num_epochs: 25
learning_rate: 0.0001
patience: 5  # Early stopping patience

save_dir: "fake_news_detection/logs/full_data_concat"